### ISSUE TITLE
Add package fails - buymeacoffe.git could not be resolved

### ISSUE THREAD

**Issue by arbyruns** [appcraftstudio/buymeacoffee#4]
I'm trying to add https://github.com/appcraftstudio/buymeacoffee.git using swift manager and I get the following error 

_because every version of buymeacoffee contains incompatible tools version and root depends on buymeacoffee 1.0.2..<2.0.0, version solving failed._

![image](https://user-images.githubusercontent.com/2520545/92638582-7c2d6a00-f2a8-11ea-86c9-464e25766e48.png)

**Comment by arbyruns** [comment]
ugh nevermind.  I can't read lol.  It's for  Xcode 12.x only.

**Comment by frboulais** [comment]
Oh yes sorry for that!
