### ISSUE TITLE
Errors after Xcode 13.0 upgrade

### ISSUE THREAD

**Issue by geohei** [appcraftstudio/buymeacoffee#9]
Hi. Upgrading to Xcode 13.0, I get the following errors with buymeacoffee.

BMCButton.swift
- `Overriding non-open property outside of its defining module`
- `Property 'configuration' with type 'BMCButton.Configuration' cannot override a property with type 'UIButton.Configuration?'`

What needs to be changed?

Thanks

**Comment by frboulais** [comment]
Oh sorry for that, will release an update by the end of the day!

**Comment by geohei** [comment]
Many thanks for the fast fix!
Now works as before.
Good job!
